In [3]:
import numpy as np
import pandas as pd

In [4]:
movies = pd.read_csv(r"tmdb_5000_movies.csv")
credits = pd.read_csv(r"tmdb_5000_credits.csv")

movies.shape

(4803, 20)

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies = movies.merge(credits, on='title')
movies.shape

(4809, 23)

In [ ]:
movies.head(1)

In [ ]:
movies.info()

In [7]:
movies = movies[['movie_id', 'genres', 'keywords', 'overview', 'title', 'cast', 'crew']]

In [ ]:
movies.head(1)

In [8]:
movies.isnull().sum()

movie_id    0
genres      0
keywords    0
overview    3
title       0
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace=True)

In [10]:
movies.duplicated().sum()

0

In [11]:
movies['genres'].loc[0]
movies['keywords'].loc[0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [12]:
import ast

def convert(data):
    li = []
    for i in ast.literal_eval(data):
        li.append(i['name'])
    return li

movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [ ]:
movies['cast'].loc[0]

In [13]:
def convert_cast(data):
    actors_list = []
    count = 0
    
    for i in ast.literal_eval(data):
        if count == 3:
            break
        else:
            actors_list.append(i['character'])
            count = count+1
    return actors_list

movies['cast'] = movies['cast'].apply(convert_cast)

In [ ]:
movies['crew'].loc[0]

In [14]:
def convert_crew(data):
    return [i['name'] for i in ast.literal_eval(data) if i['job'] == 'Director']

movies['crew'] = movies['crew'].apply(convert_crew)

In [15]:
movies['overview'] = movies['overview'].apply(lambda x: x.split(' '))

In [16]:
def space_remover(string_list):
    return [s.replace(" ", "") for s in string_list]


movies['genres'] = movies['genres'].apply(space_remover)
movies['keywords'] = movies['keywords'].apply(space_remover)
movies['cast'] = movies['cast'].apply(space_remover)
movies['crew'] = movies['crew'].apply(space_remover)

In [ ]:
movies.columns

In [ ]:
movies.head(2)

In [17]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [ ]:
movies.head(2)

In [18]:
new_df = movies[['movie_id', 'title', 'tags']]
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [19]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [20]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [59]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [ ]:
pip install nltk

In [21]:
import nltk

In [22]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [23]:
def stem(text):
    return " ".join([ps.stem(i) for i in text.split()])

In [24]:
new_df['tags'] = new_df['tags'].apply(stem)

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
similarity = cosine_similarity(vectors)
print(similarity)

[[1.         0.08858079 0.08718573 ... 0.04559608 0.         0.        ]
 [0.08858079 1.         0.06350006 ... 0.02490677 0.         0.0277137 ]
 [0.08718573 0.06350006 1.         ... 0.02451452 0.         0.        ]
 ...
 [0.04559608 0.02490677 0.02451452 ... 1.         0.03774257 0.04279605]
 [0.         0.         0.         ... 0.03774257 1.         0.08399211]
 [0.         0.0277137  0.         ... 0.04279605 0.08399211 1.        ]]

In [43]:
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    enumerated_list = list(enumerate(similarity[index]))
    print(enumerated_list)
    distances = sorted(enumerated_list, reverse=True, key= lambda x: x[1])
    movie_list = []
    
    for i in distances[1:6]:
        movie_list.append(new_df['title'].loc[i[0]])

    print(movie_list)
        
recommend("Avatar")

[(0, 1.0), (1, 0.0885807893036239), (2, 0.08718572905786445), (3, 0.07009996372327816), (4, 0.19184045508446734), (5, 0.10195592378577323), (6, 0.037470006725398436), (7, 0.15042366316917008), (8, 0.059053859535749265), (9, 0.09208185110322616), (10, 0.10269923319261937), (11, 0.09592022754223367), (12, 0.0949157995752499), (13, 0.03958262466638396), (14, 0.1316245316231641), (15, 0.06367145399670132), (16, 0.08000711205939975), (17, 0.14273829330008253), (18, 0.09824718648648241), (19, 0.08219949365267865), (20, 0.08521145659838941), (21, 0.11277677488692017), (22, 0.06003002251876642), (23, 0.09320546490018), (24, 0.056388387443460086), (25, 0.052278773405661366), (26, 0.15404884978892902), (27, 0.18944220058835154), (28, 0.11810771907149853), (29, 0.06711560552140243), (30, 0.06590621627456203), (31, 0.14309095175803563), (32, 0.08787495503274936), (33, 0.09004503377814962), (34, 0.0), (35, 0.10283867552865913), (36, 0.17348855898381338), (37, 0.07798128673650545), (38, 0.07696578428840449), (39, 0.08108108108108109), (40, 0.07194017065667525), (41, 0.17155007848855516), (42, 0.0), (43, 0.09299811099505542), (44, 0.03504998186163908), (45, 0.08219949365267865), (46, 0.13334518676566626), (47, 0.17437145811572893), (48, 0.08419653359482289), (49, 0.06105625108726635), (50, 0.11810771907149853), (51, 0.10042266465917388), (52, 0.1522038868295523), (53, 0.04317328917763455), (54, 0.027399831217559546), (55, 0.06746792083200746), (56, 0.1677890138035061), (57, 0.020878692266483083), (58, 0.06774581282657174), (59, 0.0930725988812425), (60, 0.018735003362699218), (61, 0.23995690956687135), (62, 0.08489527199560176), (63, 0.08219949365267865), (64, 0.03106848830006), (65, 0.018735003362699218), (66, 0.020712325533373332), (67, 0.17348855898381338), (68, 0.10959932487023819), (69, 0.026936179620310644), (70, 0.12683657235796025), (71, 0.07897471897389846), (72, 0.14097096860865022), (73, 0.03504998186163908), (74, 0.20518233866439894), (75, 0.15404884978892905), (76, 0.07118684968143743), (77, 0.013796056546950987), (78, 0.050141221056390024), (79, 0.061649620239508984), (80, 0.05086938251105255), (81, 0.11241002017619531), (82, 0.07352146220938079), (83, 0.18065550087085797), (84, 0.12629480039223434), (85, 0.11565903932254226), (86, 0.06475993376645182), (87, 0.1144727614064285), (88, 0.08000711205939975), (89, 0.05461037115296921), (90, 0.05264981264926564), (91, 0.1743714581157289), (92, 0.06314740019611717), (93, 0.07271792483455794), (94, 0.1553424415003), (95, 0.16967515794730187), (96, 0.08108108108108109), (97, 0.07045670884515312), (98, 0.07118684968143743), (99, 0.023980056885558418), (100, 0.07352146220938077), (101, 0.07610194341477616), (102, 0.12734290799340264), (103, 0.08094446585163528), (104, 0.058123819371909635), (105, 0.11028219331407116), (106, 0.056205010088097654), (107, 0.06314740019611717), (108, 0.1487044791289829), (109, 0.06575959492214292), (110, 0.04516387521771449), (111, 0.15404884978892902), (112, 0.08108108108108109), (113, 0.04393747751637468), (114, 0.04649905549752771), (115, 0.04559607525875532), (116, 0.048478616556371965), (117, 0.06003002251876642), (118, 0.0325558506696506), (119, 0.04355035563093422), (120, 0.0), (121, 0.11624763874381927), (122, 0.11624763874381927), (123, 0.11083777463036817), (124, 0.05937393699957594), (125, 0.0747783303855266), (126, 0.12253577034896797), (127, 0.14988002690159374), (128, 0.0), (129, 0.08710071126186844), (130, 0.02348556961505104), (131, 0.09695723311274393), (132, 0.04016906586366955), (133, 0.058123819371909635), (134, 0.1371182340382122), (135, 0.0), (136, 0.02302046277580654), (137, 0.028618190351607124), (138, 0.12996881122750908), (139, 0.12050719759100866), (140, 0.04244763599780088), (141, 0.07271792483455794), (142, 0.08336550215650926), (143, 0.08867021970429453), (144, 0.04516387521771449), (145, 0.01979131233319198), (146, 0.014530954842977409), (147, 0.058123819371909635), (148, 0.09672388203287416), (149, 0.15833049866553583), (150, 0.16861503026429298), (151, 0.21029989116983447), (152, 0.07352146220938079), (153, 0.08156473902861858), (154, 0.0533380747062665), (155, 0.020878692266483083), (156, 0.06117355427146393), (157, 0.09672388203287416), (158, 0.12951986753290365), (159, 0.06105625108726635), (160, 0.11450817448118329), (161, 0.03224129401095805), (162, 0.029526929767874632), (163, 0.07610194341477616), (164, 0.08336550215650926), (165, 0.04697113923010208), (166, 0.12119654139092992), (167, 0.09672388203287416), (168, 0.21775177815467112), (169, 0.08561170049453902), (170, 0.10793322294408637), (171, 0.04604092555161308), (172, 0.2102998911698345), (173, 0.02177517781546711), (174, 0.07897471897389846), (175, 0.06839411288813299), (176, 0.030528125543633176), (177, 0.0), (178, 0.02279803762937766), (179, 0.08585457105482137), (180, 0.022581937608857246), (181, 0.042098266797411445), (182, 0.13423121104280486), (183, 0.07218053273850816), (184, 0.16274669424134697), (185, 0.05134961659630968), (186, 0.06025359879550432), (187, 0.1438803413133505), (188, 0.02302046277580654), (189, 0.1162476387438193), (190, 0.0803381317273391), (191, 0.04956815970966097), (192, 0.047960113771116836), (193, 0.07983920607777244), (194, 0.0), (195, 0.06105625108726635), (196, 0.048478616556371965), (197, 0.036992662308349696), (198, 0.06003002251876642), (199, 0.08710071126186844), (200, 0.11314714296070713), (201, 0.0), (202, 0.024239308278185982), (203, 0.07702442489446452), (204, 0.04516387521771449), (205, 0.11314714296070713), (206, 0.08787495503274936), (207, 0.07798128673650545), (208, 0.12655439943366653), (209, 0.10762440050012628), (210, 0.08787495503274936), (211, 0.024784079854830485), (212, 0.06839411288813299), (213, 0.06070834938872646), (214, 0.0), (215, 0.06590621627456203), (216, 0.06003002251876642), (217, 0.08710071126186844), (218, 0.04109974682633932), (219, 0.09672388203287416), (220, 0.2101050788156825), (221, 0.047457899787624956), (222, 0.07916524933276792), (223, 0.10397504898200727), (224, 0.06263607679944924), (225, 0.047457899787624956), (226, 0.03106848830006), (227, 0.08585457105482137), (228, 0.1139901881468883), (229, 0.10959932487023819), (230, 0.09428928580058928), (231, 0.0), (232, 0.10810810810810811), (233, 0.11028219331407116), (234, 0.08219949365267865), (235, 0.07610194341477616), (236, 0.11624763874381927), (237, 0.06575959492214292), (238, 0.11168711865749101), (239, 0.12866255886641637), (240, 0.047960113771116836), (241, 0.07897471897389846), (242, 0.08108108108108109), (243, 0.09394227846020416), (244, 0.09672388203287416), (245, 0.08219949365267865), (246, 0.07804228110385686), (247, 0.0), (248, 0.04604092555161308), (249, 0.1289651760438322), (250, 0.0), (251, 0.047457899787624956), (252, 0.020878692266483083), (253, 0.06420877537090426), (254, 0.06420877537090426), (255, 0.0), (256, 0.09672388203287416), (257, 0.05479966243511909), (258, 0.016956460837017517), (259, 0.0644825880219161), (260, 0.21010507881568247), (261, 0.024784079854830485), (262, 0.1098436937909367), (263, 0.10067340828210367), (264, 0.0), (265, 0.028194193721730043), (266, 0.10146925788636821), (267, 0.0685591170191061), (268, 0.05264981264926564), (269, 0.051987524491003634), (270, 0.09208185110322616), (271, 0.07352146220938079), (272, 0.029061909685954818), (273, 0.020391184757154644), (274, 0.09126381430107945), (275, 0.1526406277181659), (276, 0.06327719971683327), (277, 0.053494721371611896), (278, 0.12253577034896797), (279, 0.09394227846020416), (280, 0.0), (281, 0.0665026647782209), (282, 0.04604092555161308), (283, 0.028618190351607124), (284, 0.018857857160117855), (285, 0.02023611646290882), (286, 0.0803381317273391), (287, 0.05405405405405406), (288, 0.025070610528195012), (289, 0.04355035563093422), (290, 0.06711560552140244), (291, 0.05134961659630968), (292, 0.09158437663089952), (293, 0.027788500718836418), (294, 0.13334518676566626), (295, 0.10959932487023819), (296, 0.03874921291460643), (297, 0.04559607525875532), (298, 0.0), (299, 0.0558435593287455), (300, 0.1754942736973651), (301, 0.11314714296070713), (302, 0.06475993376645182), (303, 0.029061909685954818), (304, 0.06711560552140244), (305, 0.1821250481661794), (306, 0.1316245316231641), (307, 0.11125134985317059), (308, 0.0685591170191061), (309, 0.059053859535749265), (310, 0.03120812265889869), (311, 0.1559625734730109), (312, 0.10529962529853128), (313, 0.04901430813958719), (314, 0.0), (315, 0.08718572905786445), (316, 0.0), (317, 0.0), (318, 0.0), (319, 0.10762440050012628), (320, 0.03163859985841663), (321, 0.0), (322, 0.21621621621621623), (323, 0.03106848830006), (324, 0.02279803762937766), (325, 0.08108108108108109), (326, 0.05264981264926564), (327, 0.028618190351607124), (328, 0.024784079854830485), (329, 0.08108108108108109), (330, 0.10529962529853128), (331, 0.09299811099505542), (332, 0.10959932487023819), (333, 0.050734628943184104), (334, 0.1487044791289829), (335, 0.04697113923010208), (336, 0.07352146220938077), (337, 0.04649905549752771), (338, 0.0), (339, 0.04604092555161308), (340, 0.04956815970966097), (341, 0.08585457105482137), (342, 0.18266554145039696), (343, 0.018266554145039696), (344, 0.030528125543633176), (345, 0.02302046277580654), (346, 0.027788500718836418), (347, 0.0), (348, 0.050141221056390024), (349, 0.08219949365267865), (350, 0.04956815970966097), (351, 0.0), (352, 0.02702702702702703), (353, 0.04355035563093422), (354, 0.022371868507134143), (355, 0.03796631983009995), (356, 0.12655439943366653), (357, 0.0), (358, 0.05479966243511909), (359, 0.030528125543633176), (360, 0.021402925123634755), (361, 0.07798128673650545), (362, 0.10067340828210367), (363, 0.09687303228651607), (364, 0.023728949893812478), (365, 0.07798128673650545), (366, 0.058123819371909635), (367, 0.0), (368, 0.1342312110428049), (369, 0.12535305264097507), (370, 0.0533380747062665), (371, 0.09913631941932194), (372, 0.04901430813958719), (373, 0.18380365552345193), (374, 0.030528125543633176), (375, 0.06314740019611717), (376, 0.07045670884515312), (377, 0.0), (378, 0.0), (379, 0.04767914993707312), (380, 0.05479966243511909), (381, 0.08489527199560176), (382, 0.0), (383, 0.0863465783552691), (384, 0.03001501125938321), (385, 0.0), (386, 0.022371868507134143), (387, 0.024784079854830485), (388, 0.0), (389, 0.09320546490018), (390, 0.023249527748763855), (391, 0.05733298225836872), (392, 0.03224129401095805), (393, 0.0), (394, 0.025993762245501817), (395, 0.05264981264926564), (396, 0.04516387521771449), (397, 0.05479966243511909), (398, 0.0), (399, 0.02177517781546711), (400, 0.09158437663089952), (401, 0.03224129401095805), (402, 0.08219949365267865), (403, 0.08351476906593233), (404, 0.06327719971683327), (405, 0.055577001437672836), (406, 0.019241446072101123), (407, 0.022167554926073633), (408, 0.03427955850955305), (409, 0.0), (410, 0.09592022754223367), (411, 0.05264981264926564), (412, 0.15660307954993902), (413, 0.13699915608779772), (414, 0.03106848830006), (415, 0.04859614064775855), (416, 0.05264981264926564), (417, 0.028194193721730043), (418, 0.030528125543633176), (419, 0.06974858324629157), (420, 0.11510231387903269), (421, 0.024239308278185982), (422, 0.12006004503753284), (423, 0.04244763599780088), (424, 0.03902114055192843), (425, 0.06532553344640132), (426, 0.05514109665703558), (427, 0.02702702702702703), (428, 0.05381220025006314), (429, 0.0), (430, 0.0665026647782209), (431, 0.02279803762937766), (432, 0.11624763874381928), (433, 0.03427955850955305), (434, 0.0), (435, 0.03504998186163908), (436, 0.0), (437, 0.02702702702702703), (438, 0.1283740414907742), (439, 0.05405405405405406), (440, 0.02348556961505104), (441, 0.0533380747062665), (442, 0.047457899787624956), (443, 0.06314740019611717), (444, 0.0), (445, 0.10397504898200727), (446, 0.023980056885558418), (447, 0.06711560552140243), (448, 0.02196873875818734), (449, 0.11624763874381927), (450, 0.04244763599780088), (451, 0.07702442489446452), (452, 0.030528125543633176), (453, 0.025367314471592052), (454, 0.12119654139092992), (455, 0.08351476906593233), (456, 0.04317328917763455), (457, 0.0885807893036239), (458, 0.03609026636925408), (459, 0.029526929767874632), (460, 0.024507154069793594), (461, 0.16673100431301852), (462, 0.03321361106966265), (463, 0.03001501125938321), (464, 0.0), (465, 0.0), (466, 0.14704292441876154), (467, 0.1061190899945022), (468, 0.029526929767874632), (469, 0.057724338216303364), (470, 0.04649905549752771), (471, 0.06532553344640132), (472, 0.11115400287534567), (473, 0.09592022754223367), (474, 0.0), (475, 0.04516387521771449), (476, 0.14019992744655632), (477, 0.0), (478, 0.05548899346252455), (479, 0.08569889627388262), (480, 0.10146925788636821), (481, 0.0), (482, 0.022581937608857246), (483, 0.1342312110428049), (484, 0.03163859985841663), (485, 0.05264981264926564), (486, 0.08099356774626426), (487, 0.1342312110428049), (488, 0.06746792083200746), (489, 0.0), (490, 0.14019992744655632), (491, 0.09755285137982107), (492, 0.06906138832741962), (493, 0.03149313426096192), (494, 0.0), (495, 0.18316875326179907), (496, 0.0), (497, 0.0), (498, 0.0685591170191061), (499, 0.0), (500, 0.02567480829815484), (501, 0.07696578428840449), (502, 0.14856672599230308), (503, 0.07435223956449145), (504, 0.0), (505, 0.14019992744655632), (506, 0.030528125543633176), (507, 0.26601065911288363), (508, 0.1487044791289829), (509, 0.022371868507134143), (510, 0.10269923319261937), (511, 0.09320546490018), (512, 0.028618190351607124), (513, 0.1797236580870839), (514, 0.04244763599780088), (515, 0.025367314471592052), (516, 0.029526929767874632), (517, 0.0), (518, 0.04433510985214727), (519, 0.0), (520, 0.0), (521, 0.025993762245501817), (522, 0.02348556961505104), (523, 0.050141221056390024), (524, 0.0), (525, 0.04317328917763455), (526, 0.02702702702702703), (527, 0.03504998186163908), (528, 0.022581937608857246), (529, 0.18416370220645234), (530, 0.05723638070321425), (531, 0.04649905549752771), (532, 0.02177517781546711), (533, 0.0533380747062665), (534, 0.09491579957524991), (535, 0.10146925788636821), (536, 0.1186447494690624), (537, 0.07009996372327816), (538, 0.0), (539, 0.2657423679108717), (540, 0.07521183158458504), (541, 0.10274936706584831), (542, 0.03771571432023571), (543, 0.09592022754223367), (544, 0.056388387443460086), (545, 0.02632490632463282), (546, 0.05723638070321425), (547, 0.08336550215650926), (548, 0.0), (549, 0.17897494805707315), (550, 0.021049133398705722), (551, 0.036992662308349696), (552, 0.0), (553, 0.030528125543633176), (554, 0.0), (555, 0.10171668390084186), (556, 0.02702702702702703), (557, 0.12535305264097507), (558, 0.0), (559, 0.03106848830006), (560, 0.03653310829007939), (561, 0.03287979746107146), (562, 0.03224129401095805), (563, 0.07435223956449145), (564, 0.09158437663089952), (565, 0.03609026636925408), (566, 0.022581937608857246), (567, 0.025993762245501817), (568, 0.15007505629691603), (569, 0.03902114055192843), (570, 0.07009996372327816), (571, 0.042098266797411445), (572, 0.10701462561817376), (573, 0.02122381799890044), (574, 0.023728949893812478), (575, 0.04697113923010208), (576, 0.0533380747062665), (577, 0.1973593560521103), (578, 0.036992662308349696), (579, 0.14097096860865022), (580, 0.025367314471592052), (581, 0.15819299929208316), (582, 0.2484013136974297), (583, 0.038482892144202245), (584, 0.08489527199560176), (585, 0.024239308278185982), (586, 0.048478616556371965), (587, 0.09491579957524991), (588, 0.02702702702702703), (589, 0.11389895949029986), (590, 0.03163859985841663), (591, 0.06475993376645182), (592, 0.02177517781546711), (593, 0.0), (594, 0.05134961659630968), (595, 0.19184045508446734), (596, 0.09491579957524991), (597, 0.09158437663089952), (598, 0.03771571432023571), (599, 0.026495295846634775), (600, 0.06590621627456203), (601, 0.03338437626246901), (602, 0.09394227846020416), (603, 0.051987524491003634), (604, 0.058123819371909635), (605, 0.022581937608857246), (606, 0.0), (607, 0.07916524933276792), (608, 0.030528125543633176), (609, 0.048478616556371965), (610, 0.05881716976750462), (611, 0.02279803762937766), (612, 0.061649620239508984), (613, 0.03771571432023571), (614, 0.06774581282657174), (615, 0.06327719971683327), (616, 0.03106848830006), (617, 0.051987524491003634), (618, 0.0863465783552691), (619, 0.0), (620, 0.0), (621, 0.07009996372327816), (622, 0.021586644588817275), (623, 0.0), (624, 0.10514994558491725), (625, 0.03224129401095805), (626, 0.08336550215650926), (627, 0.11314714296070713), (628, 0.0), (629, 0.048478616556371965), (630, 0.024784079854830485), (631, 0.04355035563093422), (632, 0.10397504898200727), (633, 0.02302046277580654), (634, 0.07521183158458504), (635, 0.06906138832741962), (636, 0.023728949893812478), (637, 0.025367314471592052), (638, 0.03504998186163908), (639, 0.0), (640, 0.06263607679944924), (641, 0.0), (642, 0.0), (643, 0.10397504898200727), (644, 0.050734628943184104), (645, 0.04317328917763455), (646, 0.05405405405405406), (647, 0.04901430813958719), (648, 0.03224129401095805), (649, 0.0), (650, 0.10269923319261937), (651, 0.0), (652, 0.036309662106579856), (653, 0.11314714296070713), (654, 0.1011805823145441), (655, 0.023728949893812478), (656, 0.0), (657, 0.03446739311292904), (658, 0.04956815970966097), (659, 0.025993762245501817), (660, 0.09863939238321438), (661, 0.15833049866553583), (662, 0.0), (663, 0.0), (664, 0.06213697660012), (665, 0.06839411288813299), (666, 0.07352146220938079), (667, 0.0), (668, 0.14019992744655632), (669, 0.03771571432023571), (670, 0.01793740008335438), (671, 0.06974858324629157), (672, 0.02702702702702703), (673, 0.05812381937190965), (674, 0.10887588907733556), (675, 0.10701462561817378), (676, 0.028618190351607124), (677, 0.024784079854830485), (678, 0.12427395320024), (679, 0.0), (680, 0.07352146220938079), (681, 0.029061909685954818), (682, 0.020712325533373332), (683, 0.048478616556371965), (684, 0.0), (685, 0.03355780276070122), (686, 0.03001501125938321), (687, 0.10810810810810811), (688, 0.04355035563093422), (689, 0.0), (690, 0.02567480829815484), (691, 0.06213697660012), (692, 0.10356162766686666), (693, 0.03587480016670876), (694, 0.022581937608857246), (695, 0.06711560552140244), (696, 0.02054987341316966), (697, 0.0), (698, 0.04474373701426829), (699, 0.03874921291460643), (700, 0.029061909685954818), (701, 0.058123819371909635), (702, 0.023249527748763855), (703, 0.021049133398705722), (704, 0.06314740019611717), (705, 0.024507154069793594), (706, 0.04393747751637468), (707, 0.0), (708, 0.024507154069793594), (709, 0.020878692266483083), (710, 0.05894831189188944), (711, 0.05405405405405406), (712, 0.0), (713, 0.02702702702702703), (714, 0.0), (715, 0.10283867552865913), (716, 0.028194193721730043), (717, 0.0), (718, 0.08787495503274936), (719, 0.0), (720, 0.05479966243511909), (721, 0.03427955850955305), (722, 0.0), (723, 0.025367314471592052), (724, 0.024239308278185982), (725, 0.0), (726, 0.0), (727, 0.03134965682110385), (728, 0.07435223956449145), (729, 0.050734628943184104), (730, 0.029526929767874632), (731, 0.05405405405405406), (732, 0.06774581282657174), (733, 0.06367145399670132), (734, 0.06420877537090426), (735, 0.06839411288813299), (736, 0.03001501125938321), (737, 0.07702442489446452), (738, 0.0), (739, 0.04244763599780088), (740, 0.10356162766686666), (741, 0.05723638070321425), (742, 0.027399831217559546), (743, 0.023980056885558418), (744, 0.05723638070321425), (745, 0.09004503377814962), (746, 0.0665026647782209), (747, 0.03929887459459296), (748, 0.03874921291460643), (749, 0.0), (750, 0.04317328917763455), (751, 0.03427955850955305), (752, 0.08710071126186844), (753, 0.028618190351607124), (754, 0.10793322294408637), (755, 0.056573571480353566), (756, 0.030528125543633176), (757, 0.024239308278185982), (758, 0.023249527748763855), (759, 0.04433510985214727), (760, 0.05405405405405406), (761, 0.029061909685954818), (762, 0.06213697660012), (763, 0.0), (764, 0.029061909685954818), (765, 0.02567480829815484), (766, 0.023249527748763855), (767, 0.

In [1]:
import pickle

In [31]:
pickle.dump(new_df.to_dict(), open('movie_list_dict.pkl', 'wb'))

In [32]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))